hdhomerun_host = "192.168.1.12"
hdhr_transcode = false
ffmpeg_path = "/ffmpeg/bin/ffmpeg"
transcoding_path = "./tmp"
port = "8888"
hd_start = 500

[ffmpeg]
threads = 4
ac = 2
acodec = "libfdk_aac"
vcodec = "libx264"
framerate = "29.97"
h264_preset = "superfast"
hls_time = 2
hls_wrap = 40
options = "-loglevel warning -async 1  -tune zerolatency -flags -global_header -fflags +genpts -map 0:0 -map 0:1"

[channel_logos]
5136 = "cbs.png"
